apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deploy
  labels:
    app: order-app
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
    spec:
      containers:
      - name: order-container
        image: us-central1-docker.pkg.dev/k8s-cloud-478700/my-repo/order-app:v3
        ports:
        - containerPort: 8080
        
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"